services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    env_file:
      - .env 
    depends_on:
      ollama:
        condition: service_healthy
  
  ollama:
    image: ollama/ollama:0.4.0
    volumes:
      - ./models:/root/.ollama
      - ./start_ollama.sh:/usr/local/bin/start_ollama.sh
    ports:
      - "11434:11434"
    env_file:
      - .env 
    entrypoint: ["/usr/local/bin/start_ollama.sh"] #["sh", "-c", "ollama serve && ollama run llama3.2"]
    healthcheck:
      test: ["CMD-SHELL", "ollama --version && ollama ps || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Reserva recursos de GPU
